// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tqghimskakqggzaoedzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZ2hpbXNrYWtxZ2d6YW9lZHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2ODcyMTEsImV4cCI6MjA5NDI2MzIxMX0.faNQUO86o2ZdjkGkJyC91FaQSLIEWfCfUXlOJJhrciE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);